// Generated by https://quicktype.io

export interface IProductsResponse {
  id: string;
  name: string;
  stock: number;
  description: string;
  userProductDetails: null;
  price: number;
  imageUrl: string;
}
