// Generated by https://quicktype.io

export interface Product {
  productId?:      number;
  name:           string;
  description:    string;
  cost:           number;
  price:          number;
  stock:          number;
  invoiceDetails?: null;
}
