// Generated by https://quicktype.io

export interface Invoice {
  invoiceId?:      number;
  invoiceNumber:  number;
  invoiceDate:    string;
  concept:        string;
  subtotal?:       number;
  total?:          number;
  tax?:            number;
  anulado?:        boolean;
  userId:         number;
  user?:           null;
  invoiceDetails: InvoiceDetails[];
}

export interface InvoiceDetails {
  productId: number,
  quantitySold: number,
  product?: []
}
